# Generated by Django 4.1.4 on 2023-01-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='hit_count',
            field=models.IntegerField(default=0),
        ),
    ]
